var OX_placement,OX_dfp_ads,OX_dfp_options;
(function(){function w(a){h&&console.log(k()+" Registering Header with ZEDO - "+a);g.hdq[a]=!1}function x(a,c){h&&console.log(k()+" Loaded Header - "+a);g.hdq[a]=!0;a:{for(var d in g.hdq)if(!g.hdq[d])break a;y(c,"response")}}function C(a,c){h&&console.log(k()+" Entered Header Render");var d=this.responses[c];"openx"==d&&"OX_zedo"in window?(d=OX_zedo.dfp_bidder.getPriceMap(),h&&console.log(k()+" Rendering openx"),a.write(d[c].ad),a.close()):"prebid"==d&&(h&&console.log(k()+" Rendering prebid"),window.pbjs.renderAd(a,
c))}function D(a,c,d,e){OX_placement=e.placement;OX_dfp_ads=[[e.cf,[c+"x"+d],OX_placement]];g.oxPlmt=OX_placement;OX_dfp_options={callback:function(){x("openx",a)}};E()}function E(){var a=window.zi_nid||window.zflag_nid||window.zslu_nid||"",c=document.createElement("script");c.async=!0;c.type="text/javascript";var d="https:"===document.location.protocol;"3632"==a||"3628"==a||"3614"==a?(h&&console.log(k()+" Called new openx file:nc=123456-zedo_2"),c.src=(d?"https:":"http:")+"//zedo-d.openx.net/w/1.0/jstag?nc=123456-zedo_2&oxns=zedo"):
c.src=(d?"https:":"http:")+"//zedo-d.openx.net/w/1.0/jstag?nc=123456-zedo&oxns=zedo";a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(c,a)}function y(a,c){if(!pbjs.initAdserverSet){clearTimeout(q);pbjs.initAdserverSet=!0;var d="",e=0,f=0,t="",m="",n="",r="";for(n in g.hdq)if(g.hdq[n]){if("openx"==n&&"OX_zedo"in window&&0!=OX_zedo.dfp_bidder.getPrice(g.oxPlmt)&&""!==OX_zedo.dfp_bidder.getPrice(g.oxPlmt)){var t=n,e=OX_zedo.dfp_bidder.getPrice(g.oxPlmt),e=Number(e)/100,m=g.oxPlmt,
l=OX_zedo.dfp_bidder.getPriceMap(),p=l[m].price.split(",");1<p.length&&(e=Number(p[0])/100,-1<p[1].indexOf("pmp")?(r=p[2],f=1,h&&console.log(k()+" Id : "+m+" ----- Price map : "+l[m].price)):(r="",f=0));h&&console.log(k()+" openx price before Rev share:"+e);l=f?e*z/100:e*A/100;e=e>l?e-l:e;a.zGlobalHeader.setResponse(m,n);h&&console.log("openx price : "+e+", placement : "+g.oxPlmt)}"prebid"==n&&"undefined"!==typeof pbjs.libLoaded&&"response"===c&&(l=pbjs.getAdserverTargetingForAdUnitCode()[a.zAdcode],
h&&(console.log(k()+" Are all bids available? : "+pbjs.allBidsAvailable()),console.log(k()+" Dumping all bid objects to console:"),console.log(pbjs.getBidResponses(a.zAdcode)),console.log(k()+" Prebid Response with : "),console.log(l)),"undefined"!==typeof l&&"undefined"!==typeof l.hb_cpm&&l.hb_cpm>e&&(e=l.hb_cpm,t=l.hb_bidder,m=l.hb_adid,a.zGlobalHeader.setResponse(m,n)))}0<e&&(d={cpm:e,bidNm:t,adid:m,ispmp:f,pmp:r},h&&console.log(d));a.zCallbackFunc(d)}}function F(a,c,d){for(var e="",f=0,g=d.length;f<
g;f++)e+=d[f].name+"_";pbjs.biddersName=e;var m=function(){var d="undefined"!==c&&""!==c?c:400;pbjs.bidderTimeout=d-200;q=setTimeout(function(){clearTimeout(q);h&&console.log(k()+" Timeout occured");pbjs.initAdserverSet=!1;y(a,"timeout")},d)};(function(){h&&console.log(k()+" Made call to prebid.js");try{var a=document.createElement("script"),d=!1,c=new Date,e=c.getMonth()+1+""+c.getDate()+""+c.getHours()+""+c.getMinutes()+""+c.getSeconds();filepath="http:"===location.protocol?"http://c14.zedo.com/utils/prebid/v0.8.1/prebid.js?"+
e:"https://ss3.zedo.com/utils/prebid/v0.8.1/prebid.js?"+e;a.type="text/javascript";a.src=filepath;a.id="zd_prebid";a.async="true";a.onload=a.onreadystatechange=function(){var a=this.readyState;d||a&&"complete"!=a&&"loaded"!=a||(d=!0,h&&console.log(k()+" ZINC Log: Prebid.js Loaded"),m())};var f=document.getElementsByTagName("head")[0];f.insertBefore(a,f.firstChild)}catch(u){}})()}function G(a){for(var c=a.zBids,d=[{code:a.zAdcode,sizes:[[c.width,c.height]],bids:[]}],e=0,f=!1,g=!1,m=0,n=0,r=0,l=0,p=
0,q=0,u,v=0;v<c.bidders.length;v++){var b=c.bidders[v];"openx"==b.name&&(b.rvs&&(A=b.rvs),b.prvs&&(z=b.prvs),g=!0,u=b);"aol"==b.name&&(b.rvs&&(m=b.rvs),d[0].bids.push({bidder:b.name,params:{network:b.network,placement:b.placement,sizeId:b.sizeId,alias:b.alias}}),f=!0);"brealtime"==b.name&&(b.rvs&&(n=b.rvs),d[0].bids.push({bidder:b.name,params:{placementId:b.placementId}}),e=1,f=!0);"pulsepoint"==b.name&&(b.rvs&&(r=b.rvs),d[0].bids.push({bidder:b.name,params:{cf:b.cf,cp:b.cp,ct:b.ct}}),f=!0);"appnexus"==
b.name&&(b.rvs&&(l=b.rvs),d[0].bids.push({bidder:b.name,params:{placementId:b.placementId}}),f=!0);"sovrn"==b.name&&(b.rvs&&(p=b.rvs),d[0].bids.push({bidder:b.name,params:{tagid:b.tagid}}),f=!0);"criteo"==b.name&&(b.rvs&&(q=b.rvs),d[0].bids.push({bidder:b.name,params:{nid:b.nid,cookieName:b.cookieName,varName:b.varName,zoneMap:b.zoneMap}}),f=!0)}g&&w("openx");f&&w("prebid");g&&D(a,c.width,c.height,u);f&&pbjs.que.push(function(){pbjs.addAdUnits(d);1==e&&pbjs.aliasBidder("appnexus","brealtime");pbjs.addCallback("adUnitBidsBack",
function(a){h&&console.log(k()+" Ad unit bids back for : "+a)});pbjs.requestBids({bidsBackHandler:function(b){x("prebid",a)}});pbjs.bidderSettings={standard:{adserverTargeting:[{key:"hb_bidder",val:function(a){return a.bidderCode}},{key:"hb_adid",val:function(a){return a.adId}},{key:"hb_cpm",val:function(a){return a.cpm}}]},aol:{bidCpmAdjustment:function(a){var b=a*m/100;return a>b?a-b:a}},brealtime:{bidCpmAdjustment:function(a){var b=a*n/100;return a>b?a-b:a}},pulsepoint:{bidCpmAdjustment:function(a){var b=
a*r/100;return a>b?a-b:a}},appnexus:{bidCpmAdjustment:function(a){var b=a*l/100;return a>b?a-b:a}},sovrn:{bidCpmAdjustment:function(a){var b=a*p/100;return a>b?a-b:a}},criteo:{bidCpmAdjustment:function(a){var b=a*q/100;return a>b?a-b:a}}}})}var B=window.location.href.match(/[?&]pbjs_debug=([^&#]+)/),h=B&&"true"===B[1]?1:0;window.pbjs=window.pbjs||{};window.pbjs.que=window.pbjs.que||[];var q=0,A=0,z=0,g={hdq:{}},k=function(){var a=new Date;return a.getHours()+":"+a.getMinutes()+":"+a.getSeconds()+
":"+a.getMilliseconds()},H=function(a,c,d,e,f){return{zAdcode:a,zBids:c,zTimeout:d,zCallbackFunc:e,zGlobalHeader:f,init:function(){h&&console.log(k()+" Initialize header bidding");F(this,this.zTimeout,this.zBids.bidders);G(this)}}};window.ZHeaderBids=function(){return{bids:[],responses:{},renderAd:C,getHeaderBid:function(a,c,d,e){a=new H(a,c,d,e,this);this.bids.push(a);return a},setResponse:function(a,c){this.responses[a]=c}}}})();